//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.09 at 05:55:17 PM IST 
//


package forum.server.persistencelayer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_numOfMsgs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="_allUsers" type="{}UserType" maxOccurs="unbounded"/>
 *         &lt;element name="_allMessages" type="{}MessageType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numOfMsgs",
    "allUsers",
    "allMessages"
})
@XmlRootElement(name = "ForumType")
public class ForumType {

    @XmlElement(name = "_numOfMsgs")
    protected int numOfMsgs;
    @XmlElement(name = "_allUsers", required = true)
    protected List<UserType> allUsers;
    @XmlElement(name = "_allMessages", required = true)
    protected List<MessageType> allMessages;

    /**
     * Gets the value of the numOfMsgs property.
     * 
     */
    public int getNumOfMsgs() {
        return numOfMsgs;
    }

    /**
     * Sets the value of the numOfMsgs property.
     * 
     */
    public void setNumOfMsgs(int value) {
        this.numOfMsgs = value;
    }

    /**
     * Gets the value of the allUsers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allUsers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllUsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserType }
     * 
     * 
     */
    public List<UserType> getAllUsers() {
        if (allUsers == null) {
            allUsers = new ArrayList<UserType>();
        }
        return this.allUsers;
    }

    /**
     * Gets the value of the allMessages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allMessages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageType }
     * 
     * 
     */
    public List<MessageType> getAllMessages() {
        if (allMessages == null) {
            allMessages = new ArrayList<MessageType>();
        }
        return this.allMessages;
    }

}
